version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jakartaee11-app

    ports:
      - "8080:8080"
      - "9990:9990"

    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx2g
        -Djava.net.preferIPv4Stack=true

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5